<!DOCTYPE html>
<html>
	<head>
		<title>BBC Radio &amp; Music Programme Finder</title>
		<meta name="viewport" content="width=device-width,initial-scale=0.5,minimum-scale=0.5,maximum-scale=2,user-scalable=1,target-densitydpi=device-dpi"/>
		<link rel="icon" href="/img/favicon.ico" type="image/x-icon"/>
		<link rel="stylesheet" href="/theme/main.css"/>
		<script src="/js/main.js"></script>
	</head>
	<body>
		<header id="masthead">
			<div id="masthead-inner">
				<a id="logo" href="http://www.bbc.co.uk">
					<img src="/img/bbc-logo.png" alt="BBC" width="84" height="24"/>
				</a>
			</div>
		</header>
		<div id="main">
			<div id="iplayer-radio">
				<img src="/img/iplayer-radio-logo.png" alt="iPlayer Radio" width="231" height="40"/>
			</div>
			<?php echo $this->content ?>
		</div>
	</body>
</html>