<h1>A 404 error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if(isset($this->reason) && $this->reason) : ?>
	
	<?php $reasons = array
			( "error-controller-cannot-dispatch" => "The requested controller was unable to dispatch the request."
			, "error-controller-not-found" => "The requested controller could not be mapped to an existing controller class."
			, "error-controller-invalid" => "The requested controller was not dispatchable."
			, "error-router-no-match" => "The requested URL could not be matched by routing." ) ?>
	<?php $reasonMessage= "We cannot determine at this time why a 404 was generated." ?>
	<?php if(isset($reasons[$this->reason])) : ?>
		<?php $reasonMessage = $reasons[$this->reason] ?>
	<?php endif ?>

	<p><?php echo $reasonMessage ?></p>

<?php endif ?>

<?php if(isset($this->controller) && $this->controller) : ?>

	<dl>
	    <dt>Controller:</dt>
	    <dd>
			<?php echo $this->escapeHtml($this->controller) ?>
			<?php if(isset($this->controller_class)
			    && $this->controller_class
			    && $this->controller_class != $this->controller) : ?>
				<?php echo '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')' ?>
			<?php endif ?>
		</dd>
	</dl>
	
<?php endif ?>
	
<?php if(isset($this->display_exceptions) && $this->display_exceptions) : ?>

	<?php if(isset($this->exception) && $this->exception instanceof Exception) : ?>
		
		<h2>Additional information:</h2>
		<h3><?php echo get_class($this->exception) ?></h3>
		<dl>
		    <dt>File:</dt>
		    <dd>
		        <pre><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
		    </dd>
		    <dt>Message:</dt>
		    <dd>
		        <pre><?php echo $this->exception->getMessage() ?></pre>
		    </dd>
		    <dt>Stack trace:</dt>
		    <dd>
		        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
		    </dd>
		</dl>
		<?php $e = $this->exception->getPrevious() ?>
		<?php if($e) : ?>
			<h2>Previous exceptions</h2>
			<ul>
			    <?php while($e) : ?>
				    <li>
				        <h3><?php echo get_class($e) ?></h3>
				        <dl>
				            <dt>File:</dt>
				            <dd>
				                <pre><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
				            </dd>
				            <dt>Message:</dt>
				            <dd>
				                <pre><?php echo $e->getMessage() ?></pre>
				            </dd>
				            <dt>Stack trace:</dt>
				            <dd>
				                <pre><?php echo $e->getTraceAsString() ?></pre>
				            </dd>
				        </dl>
				    </li>
			    	<?php $e = $e->getPrevious() ?>
			    <?php endwhile ?>
			</ul>
		<?php endif ?>

	<?php else : ?>	
		<h3>No Exception available</h3>	
	<?php endif ?>

<?php endif ?>
